<?php
/**
 * ISO 4217 current currency and funds catalog.
 *
 * Generated from SIX List One published 2026-01-01.
 *
 * @package YoBooking
 */

namespace YoBooking\Payments;

defined( 'ABSPATH' ) || exit;

/**
 * Provides the complete current ISO 4217 List One code set.
 */
final class CurrencyCatalog {
	/** @return array */
	public static function all() {
		return array(
			'AED' => array( 'name' => 'UAE Dirham', 'numeric' => '784', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'AFN' => array( 'name' => 'Afghani', 'numeric' => '971', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ALL' => array( 'name' => 'Lek', 'numeric' => '008', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'AMD' => array( 'name' => 'Armenian Dram', 'numeric' => '051', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'AOA' => array( 'name' => 'Kwanza', 'numeric' => '973', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ARS' => array( 'name' => 'Argentine Peso', 'numeric' => '032', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'AUD' => array( 'name' => 'Australian Dollar', 'numeric' => '036', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'AWG' => array( 'name' => 'Aruban Florin', 'numeric' => '533', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'AZN' => array( 'name' => 'Azerbaijan Manat', 'numeric' => '944', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BAM' => array( 'name' => 'Convertible Mark', 'numeric' => '977', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BBD' => array( 'name' => 'Barbados Dollar', 'numeric' => '052', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BDT' => array( 'name' => 'Taka', 'numeric' => '050', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BHD' => array( 'name' => 'Bahraini Dinar', 'numeric' => '048', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'BIF' => array( 'name' => 'Burundi Franc', 'numeric' => '108', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'BMD' => array( 'name' => 'Bermudian Dollar', 'numeric' => '060', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BND' => array( 'name' => 'Brunei Dollar', 'numeric' => '096', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BOB' => array( 'name' => 'Boliviano', 'numeric' => '068', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BOV' => array( 'name' => 'Mvdol', 'numeric' => '984', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BRL' => array( 'name' => 'Brazilian Real', 'numeric' => '986', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BSD' => array( 'name' => 'Bahamian Dollar', 'numeric' => '044', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BTN' => array( 'name' => 'Ngultrum', 'numeric' => '064', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BWP' => array( 'name' => 'Pula', 'numeric' => '072', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BYN' => array( 'name' => 'Belarusian Ruble', 'numeric' => '933', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'BZD' => array( 'name' => 'Belize Dollar', 'numeric' => '084', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CAD' => array( 'name' => 'Canadian Dollar', 'numeric' => '124', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CDF' => array( 'name' => 'Congolese Franc', 'numeric' => '976', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CHE' => array( 'name' => 'WIR Euro', 'numeric' => '947', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CHF' => array( 'name' => 'Swiss Franc', 'numeric' => '756', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CHW' => array( 'name' => 'WIR Franc', 'numeric' => '948', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CLF' => array( 'name' => 'Unidad de Fomento', 'numeric' => '990', 'decimals' => 4, 'iso_minor_units' => 4 ),
			'CLP' => array( 'name' => 'Chilean Peso', 'numeric' => '152', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'CNY' => array( 'name' => 'Yuan Renminbi', 'numeric' => '156', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'COP' => array( 'name' => 'Colombian Peso', 'numeric' => '170', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'COU' => array( 'name' => 'Unidad de Valor Real', 'numeric' => '970', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CRC' => array( 'name' => 'Costa Rican Colon', 'numeric' => '188', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CUP' => array( 'name' => 'Cuban Peso', 'numeric' => '192', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CVE' => array( 'name' => 'Cabo Verde Escudo', 'numeric' => '132', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'CZK' => array( 'name' => 'Czech Koruna', 'numeric' => '203', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'DJF' => array( 'name' => 'Djibouti Franc', 'numeric' => '262', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'DKK' => array( 'name' => 'Danish Krone', 'numeric' => '208', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'DOP' => array( 'name' => 'Dominican Peso', 'numeric' => '214', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'DZD' => array( 'name' => 'Algerian Dinar', 'numeric' => '012', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'EGP' => array( 'name' => 'Egyptian Pound', 'numeric' => '818', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ERN' => array( 'name' => 'Nakfa', 'numeric' => '232', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ETB' => array( 'name' => 'Ethiopian Birr', 'numeric' => '230', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'EUR' => array( 'name' => 'Euro', 'numeric' => '978', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'FJD' => array( 'name' => 'Fiji Dollar', 'numeric' => '242', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'FKP' => array( 'name' => 'Falkland Islands Pound', 'numeric' => '238', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GBP' => array( 'name' => 'Pound Sterling', 'numeric' => '826', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GEL' => array( 'name' => 'Lari', 'numeric' => '981', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GHS' => array( 'name' => 'Ghana Cedi', 'numeric' => '936', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GIP' => array( 'name' => 'Gibraltar Pound', 'numeric' => '292', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GMD' => array( 'name' => 'Dalasi', 'numeric' => '270', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GNF' => array( 'name' => 'Guinean Franc', 'numeric' => '324', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'GTQ' => array( 'name' => 'Quetzal', 'numeric' => '320', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'GYD' => array( 'name' => 'Guyana Dollar', 'numeric' => '328', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'HKD' => array( 'name' => 'Hong Kong Dollar', 'numeric' => '344', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'HNL' => array( 'name' => 'Lempira', 'numeric' => '340', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'HTG' => array( 'name' => 'Gourde', 'numeric' => '332', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'HUF' => array( 'name' => 'Forint', 'numeric' => '348', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'IDR' => array( 'name' => 'Rupiah', 'numeric' => '360', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ILS' => array( 'name' => 'New Israeli Sheqel', 'numeric' => '376', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'INR' => array( 'name' => 'Indian Rupee', 'numeric' => '356', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'IQD' => array( 'name' => 'Iraqi Dinar', 'numeric' => '368', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'IRR' => array( 'name' => 'Iranian Rial', 'numeric' => '364', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ISK' => array( 'name' => 'Iceland Krona', 'numeric' => '352', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'JMD' => array( 'name' => 'Jamaican Dollar', 'numeric' => '388', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'JOD' => array( 'name' => 'Jordanian Dinar', 'numeric' => '400', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'JPY' => array( 'name' => 'Yen', 'numeric' => '392', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'KES' => array( 'name' => 'Kenyan Shilling', 'numeric' => '404', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'KGS' => array( 'name' => 'Som', 'numeric' => '417', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'KHR' => array( 'name' => 'Riel', 'numeric' => '116', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'KMF' => array( 'name' => 'Comorian Franc', 'numeric' => '174', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'KPW' => array( 'name' => 'North Korean Won', 'numeric' => '408', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'KRW' => array( 'name' => 'Won', 'numeric' => '410', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'KWD' => array( 'name' => 'Kuwaiti Dinar', 'numeric' => '414', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'KYD' => array( 'name' => 'Cayman Islands Dollar', 'numeric' => '136', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'KZT' => array( 'name' => 'Tenge', 'numeric' => '398', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'LAK' => array( 'name' => 'Lao Kip', 'numeric' => '418', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'LBP' => array( 'name' => 'Lebanese Pound', 'numeric' => '422', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'LKR' => array( 'name' => 'Sri Lanka Rupee', 'numeric' => '144', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'LRD' => array( 'name' => 'Liberian Dollar', 'numeric' => '430', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'LSL' => array( 'name' => 'Loti', 'numeric' => '426', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'LYD' => array( 'name' => 'Libyan Dinar', 'numeric' => '434', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'MAD' => array( 'name' => 'Moroccan Dirham', 'numeric' => '504', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MDL' => array( 'name' => 'Moldovan Leu', 'numeric' => '498', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MGA' => array( 'name' => 'Malagasy Ariary', 'numeric' => '969', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MKD' => array( 'name' => 'Denar', 'numeric' => '807', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MMK' => array( 'name' => 'Kyat', 'numeric' => '104', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MNT' => array( 'name' => 'Tugrik', 'numeric' => '496', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MOP' => array( 'name' => 'Pataca', 'numeric' => '446', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MRU' => array( 'name' => 'Ouguiya', 'numeric' => '929', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MUR' => array( 'name' => 'Mauritius Rupee', 'numeric' => '480', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MVR' => array( 'name' => 'Rufiyaa', 'numeric' => '462', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MWK' => array( 'name' => 'Malawi Kwacha', 'numeric' => '454', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MXN' => array( 'name' => 'Mexican Peso', 'numeric' => '484', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MXV' => array( 'name' => 'Mexican Unidad de Inversion (UDI)', 'numeric' => '979', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MYR' => array( 'name' => 'Malaysian Ringgit', 'numeric' => '458', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'MZN' => array( 'name' => 'Mozambique Metical', 'numeric' => '943', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'NAD' => array( 'name' => 'Namibia Dollar', 'numeric' => '516', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'NGN' => array( 'name' => 'Naira', 'numeric' => '566', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'NIO' => array( 'name' => 'Cordoba Oro', 'numeric' => '558', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'NOK' => array( 'name' => 'Norwegian Krone', 'numeric' => '578', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'NPR' => array( 'name' => 'Nepalese Rupee', 'numeric' => '524', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'NZD' => array( 'name' => 'New Zealand Dollar', 'numeric' => '554', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'OMR' => array( 'name' => 'Rial Omani', 'numeric' => '512', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'PAB' => array( 'name' => 'Balboa', 'numeric' => '590', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'PEN' => array( 'name' => 'Sol', 'numeric' => '604', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'PGK' => array( 'name' => 'Kina', 'numeric' => '598', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'PHP' => array( 'name' => 'Philippine Peso', 'numeric' => '608', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'PKR' => array( 'name' => 'Pakistan Rupee', 'numeric' => '586', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'PLN' => array( 'name' => 'Zloty', 'numeric' => '985', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'PYG' => array( 'name' => 'Guarani', 'numeric' => '600', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'QAR' => array( 'name' => 'Qatari Rial', 'numeric' => '634', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'RON' => array( 'name' => 'Romanian Leu', 'numeric' => '946', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'RSD' => array( 'name' => 'Serbian Dinar', 'numeric' => '941', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'RUB' => array( 'name' => 'Russian Ruble', 'numeric' => '643', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'RWF' => array( 'name' => 'Rwanda Franc', 'numeric' => '646', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'SAR' => array( 'name' => 'Saudi Riyal', 'numeric' => '682', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SBD' => array( 'name' => 'Solomon Islands Dollar', 'numeric' => '090', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SCR' => array( 'name' => 'Seychelles Rupee', 'numeric' => '690', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SDG' => array( 'name' => 'Sudanese Pound', 'numeric' => '938', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SEK' => array( 'name' => 'Swedish Krona', 'numeric' => '752', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SGD' => array( 'name' => 'Singapore Dollar', 'numeric' => '702', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SHP' => array( 'name' => 'Saint Helena Pound', 'numeric' => '654', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SLE' => array( 'name' => 'Leone', 'numeric' => '925', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SOS' => array( 'name' => 'Somali Shilling', 'numeric' => '706', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SRD' => array( 'name' => 'Surinam Dollar', 'numeric' => '968', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SSP' => array( 'name' => 'South Sudanese Pound', 'numeric' => '728', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'STN' => array( 'name' => 'Dobra', 'numeric' => '930', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SVC' => array( 'name' => 'El Salvador Colon', 'numeric' => '222', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SYP' => array( 'name' => 'Syrian Pound', 'numeric' => '760', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'SZL' => array( 'name' => 'Lilangeni', 'numeric' => '748', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'THB' => array( 'name' => 'Baht', 'numeric' => '764', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TJS' => array( 'name' => 'Somoni', 'numeric' => '972', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TMT' => array( 'name' => 'Turkmenistan New Manat', 'numeric' => '934', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TND' => array( 'name' => 'Tunisian Dinar', 'numeric' => '788', 'decimals' => 3, 'iso_minor_units' => 3 ),
			'TOP' => array( 'name' => 'Pa’anga', 'numeric' => '776', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TRY' => array( 'name' => 'Turkish Lira', 'numeric' => '949', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TTD' => array( 'name' => 'Trinidad and Tobago Dollar', 'numeric' => '780', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TWD' => array( 'name' => 'New Taiwan Dollar', 'numeric' => '901', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'TZS' => array( 'name' => 'Tanzanian Shilling', 'numeric' => '834', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'UAH' => array( 'name' => 'Hryvnia', 'numeric' => '980', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'UGX' => array( 'name' => 'Uganda Shilling', 'numeric' => '800', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'USD' => array( 'name' => 'US Dollar', 'numeric' => '840', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'USN' => array( 'name' => 'US Dollar (Next day)', 'numeric' => '997', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'UYI' => array( 'name' => 'Uruguay Peso en Unidades Indexadas (UI)', 'numeric' => '940', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'UYU' => array( 'name' => 'Peso Uruguayo', 'numeric' => '858', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'UYW' => array( 'name' => 'Unidad Previsional', 'numeric' => '927', 'decimals' => 4, 'iso_minor_units' => 4 ),
			'UZS' => array( 'name' => 'Uzbekistan Sum', 'numeric' => '860', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'VED' => array( 'name' => 'Bolívar Soberano', 'numeric' => '926', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'VES' => array( 'name' => 'Bolívar Soberano', 'numeric' => '928', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'VND' => array( 'name' => 'Dong', 'numeric' => '704', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'VUV' => array( 'name' => 'Vatu', 'numeric' => '548', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'WST' => array( 'name' => 'Tala', 'numeric' => '882', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'XAD' => array( 'name' => 'Arab Accounting Dinar', 'numeric' => '396', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'XAF' => array( 'name' => 'CFA Franc BEAC', 'numeric' => '950', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'XAG' => array( 'name' => 'Silver', 'numeric' => '961', 'decimals' => 4, 'iso_minor_units' => null ),
			'XAU' => array( 'name' => 'Gold', 'numeric' => '959', 'decimals' => 4, 'iso_minor_units' => null ),
			'XBA' => array( 'name' => 'Bond Markets Unit European Composite Unit (EURCO)', 'numeric' => '955', 'decimals' => 4, 'iso_minor_units' => null ),
			'XBB' => array( 'name' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'numeric' => '956', 'decimals' => 4, 'iso_minor_units' => null ),
			'XBC' => array( 'name' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'numeric' => '957', 'decimals' => 4, 'iso_minor_units' => null ),
			'XBD' => array( 'name' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'numeric' => '958', 'decimals' => 4, 'iso_minor_units' => null ),
			'XCD' => array( 'name' => 'East Caribbean Dollar', 'numeric' => '951', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'XCG' => array( 'name' => 'Caribbean Guilder', 'numeric' => '532', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'XDR' => array( 'name' => 'SDR (Special Drawing Right)', 'numeric' => '960', 'decimals' => 4, 'iso_minor_units' => null ),
			'XOF' => array( 'name' => 'CFA Franc BCEAO', 'numeric' => '952', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'XPD' => array( 'name' => 'Palladium', 'numeric' => '964', 'decimals' => 4, 'iso_minor_units' => null ),
			'XPF' => array( 'name' => 'CFP Franc', 'numeric' => '953', 'decimals' => 0, 'iso_minor_units' => 0 ),
			'XPT' => array( 'name' => 'Platinum', 'numeric' => '962', 'decimals' => 4, 'iso_minor_units' => null ),
			'XSU' => array( 'name' => 'Sucre', 'numeric' => '994', 'decimals' => 4, 'iso_minor_units' => null ),
			'XTS' => array( 'name' => 'Codes specifically reserved for testing purposes', 'numeric' => '963', 'decimals' => 4, 'iso_minor_units' => null ),
			'XUA' => array( 'name' => 'ADB Unit of Account', 'numeric' => '965', 'decimals' => 4, 'iso_minor_units' => null ),
			'XXX' => array( 'name' => 'The codes assigned for transactions where no currency is involved', 'numeric' => '999', 'decimals' => 4, 'iso_minor_units' => null ),
			'YER' => array( 'name' => 'Yemeni Rial', 'numeric' => '886', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ZAR' => array( 'name' => 'Rand', 'numeric' => '710', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ZMW' => array( 'name' => 'Zambian Kwacha', 'numeric' => '967', 'decimals' => 2, 'iso_minor_units' => 2 ),
			'ZWG' => array( 'name' => 'Zimbabwe Gold', 'numeric' => '924', 'decimals' => 2, 'iso_minor_units' => 2 ),
		);
	}
}
